language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover tests

jobs:
  include:
    - stage: deploy
      python: 3.6
      if: tag =~ /v?(\d+\.)?(\d+\.)?(\*|\d+)$/

deploy:
  # If you need to deploy files Travis has built, use the next line
  skip_cleanup: true
  # In this case we want to deploy to pypi
  provider: pypi
  # What distribution we want to deploy
  distributions: sdist bdist_wheel
  # When do we want to deploy?
  on:
    # In this case I want to deploy only when a tag is present...
    tags: true
    # ... and when tag is on master and respects the form "v0.0.0"
    branch:
      - master
      - /v?(\d+\.)?(\d+\.)?(\*|\d+)$/
  # Yourpypi username
  user: ${PYPI_USER}
  # Use the following if you don't have Travis CLI
  password : ${PYPI_PASSWORD}